version: '3.1'
services:
  email:
    image: jegyrendszer/email-test
    restart: always
    ports:
      - 5002:5000
    environment:
      - FLASK_APP=main.py
      - CONFIGDIR=
    volumes:
      - ../config.json:/config.json

