version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    expose:
      - 27017


  handle-server:
    build: "./handle-server"
    image: bencegyurus/handle-server:latest
    ports:
      - 3001:3001
    volumes:
      - ./config.json:/config.json
      - ./data:/data
      - ./handle-server/uploads:/uploads
    environment:
      - CONFIGDIR=/
      - SLACK_TOKEN=xoxp-3311554582775-3326149485602-5558132480816-b99feeab07cc6134360f9e4800c9d18b
      - TZ=Europe/Budapest
    stdin_open: true
    tty: true
    restart: always
  

  web-service:
    build : "./web-server"
    image: bencegyurus/web-server:latest
    ports:
      - 80:80
    extra_hosts:
    - "host.docker.internal:host-gateway"

  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"