apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodump
spec:
  schedule: "0 3 * * 2,4,6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:4.2
            command: ["mongodump", "--host=mongodb-service", "--out=/backup"]
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-volume-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-volume-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi