---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: handle-repo
  namespace: flux-system
spec:
  image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/handle-server
  interval: 5m0s
