apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-service
  labels:
    app: control-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-service
  template:
    metadata:
      labels:
        app: control-service
    spec:
      containers:
      - name: control-service
        image: 192.168.50.161:5000/control-service
        envFrom:
        - configMapRef:
            name: control-service-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: control-service-configmap
data:
  EMAIL_SERVER: http://email-server-service.default.svc.cluster.local
  HANDLE_SERVER: http://web-server-service.default.svc.cluster.local
  # WEB_SERVER: http://handle-server-service.default.svc.cluster.local
  WEB_SERVER: http://nginx-service.default.svc.cluster.local
  MONGO: http://mongo-service.default.svc.cluster.local
