apiVersion: apps/v1
kind: Deployment
metadata:
  name: handle-server-deployment
  labels:
    app: handle-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: handle-server
  template:
    metadata:
      labels:
        app: handle-server
    spec:
      volumes:
      - name: handle-server-volume
        persistentVolumeClaim:
          claimName: backend-uploads-pvc
      containers:
      - name: handle-server
        image: nginx
        resources:
        ports:
        - containerPort: 3001
          name: backend-open
        envFrom:
        - configMapRef:
            name: handle-server-configmap
        - secretRef:
            name: handle-server-secretmap
        volumeMounts:
        - name: handle-server-volume
          mountPath: /uploads
---
apiVersion: v1
kind: Service
metadata:
  name: handle-server-service
spec:
  selector:
    app: handle-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: backend-open
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: handle-server-configmap
data:
  EMAIL_SERVER: http://email-server-service.default.svc.cluster.local:5000
  MONGO_URI: mongodb://mongo-service.default.svc.cluster.local:27017/
  CONFIGDIR: /
---
apiVersion: v1
kind: Secret
metadata:
  name: handle-server-secretmap
type: Opaque
data:
  SLACK_TOKEN: eG94cC0zMzExNTU0NTgyNzc1LTMzMjYxNDk0ODU2MDItNTU1ODEzMjQ4MDgxNi1iOTlmZWVhYjA3Y2M2MTM0MzYwZjllNDgwMGM5ZDE4Ygo=
  APPLE_PASS_IDENTIFIER: ""
  MERCHANT: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads-pvc
spec:
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: backend-uploads
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
