apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.24
        ports:
        - containerPort: 27017
          protocol: TCP
          name: mongo
        volumeMounts:
        - mountPath: /data/db
          name: mongo-volume
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvclaim
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-service
# spec:
#   selector:
#     app: mongo
#   ports:
#   - port: 27017
#     targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvclaim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi