apiVersion: v1
kind: Pod
metadata:
  name: uptime-kuma-pod
  labels:
    app: uptime-kuma
spec:
  containers:
  - name: uptime-kuma
    image: louislam/uptime-kuma:latest
    env:
    - name: UPTIME_KUMA_PORT
      value: "3001"
    ports:
    - name: dash-port
      containerPort: 3001
      protocol: TCP
    volumeMounts:
    - mountPath: /app/data
      name: pvc
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: uptime-kuma-pvc
      readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
spec:
  type: LoadBalancer
  selector:
    app: uptime-kuma
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001