apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jegyrendszer-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: <name|path>
      version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: jegyrendszer-helmrepo
        namespace: flux-system
      interval: 1m
  values:
    handle:
      storageClass: nfs
    replication:
      web: 2
      handle: 2
    versions:
      handle_tag: 1.0 # {"$imagepolicy": "flux-system:handle:tag"}
      web_tag: 1.0 # {"$imagepolicy": "flux-system:web:tag"}