apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jegyrendszer-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana/loki
      version: '5.38.x'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
      interval: 1m
  values:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'