apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongo-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnami/mongodb
      version: '14.3.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: flux-system
      interval: 1m
  values:
    architecture: replicaset
    replicaCount: 2
    auth:
      enabled: true
      rootUser: root
      rootPassword: "root"
    image:
      tag: 4.2.21-debian-10-r8
    metrics:
      enabled: true