apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnami/redis
      version: '18.12.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: default
      interval: 1m
  values:
    architecture: standalone
    auth:
      enabled: true
      password: "root"