name: "Build Android app"

on: 
  push:
    paths:
      - App/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./App
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenJDK 17 (JDK & JRE)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk openjdk-17-jre
          java -version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Installing packages
        run: |
             npm install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
     
      - name: Build application
        run: |
             unset _JAVA_OPTIONS
             unset JAVA_TOOL_OPTIONS
             cd android
             ./gradlew clean
             ./gradlew assembleRelease

      - name: List directory of releases
        run: |
          ls android/app/build/outputs/apk/release/

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: android/app/build/outputs/apk/release/*.apk

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade
      
      - name: Upload APK to Minio via AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_BUCKET: jegyrendszer-app
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          GIT_TAG: ${{ github.run_number }}
        run: |
            aws configure set default.s3.signature_version s3v4
            aws --endpoint-url $MINIO_ENDPOINT s3 cp android/app/build/outputs/apk/release/app-arm64-v8a-release.apk s3://$MINIO_BUCKET/app-arm64-v8a-release-$GIT_TAG.apk
            aws --endpoint-url $MINIO_ENDPOINT s3 cp android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk s3://$MINIO_BUCKET/app-armeabi-v7a-release-$GIT_TAG.apk
            aws --endpoint-url $MINIO_ENDPOINT s3 cp android/app/build/outputs/apk/release/app-x86-release.apk s3://$MINIO_BUCKET/app-x86-release-$GIT_TAG.apk
            aws --endpoint-url $MINIO_ENDPOINT s3 cp android/app/build/outputs/apk/release/app-x86_64-release.apk s3://$MINIO_BUCKET/app-x86_64-release-$GIT_TAG.apk