---
name: Build and push WELLHELLO TICKET to GCP
on: 
  push:
    paths:
      - wellhello_api/**
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: wellhello_api
      PROJECT_ID: agora-jegyrendszer
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: europe-west3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest ./wellhello_api

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ github.run_number }}
      run: |-
        docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/jegyrendszer/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/jegyrendszer/$IMAGE_NAME:1.20.$GIT_TAG
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/jegyrendszer/$IMAGE_NAME:latest
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/jegyrendszer/$IMAGE_NAME:1.20.$GIT_TAG

    # - name: Change Chart values
    #   run: |
    #     cd deployment/jegyrendszer
    #     sed 's/handle_tag: .*/handle_tag: '${{ github.run_number }}'/' values.yaml > temp.yaml && mv temp.yaml values.yaml
    #     git config --global user.name 'GitHub Actions'
    #     git config --global user.email 'actions@github.com'
    #     git add values.yaml
    #     git commit -m "Change release tag in values.yaml"
    #     git push